# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=5, unique=True)),
                ('code', models.TextField()),
                ('classification', models.TextField()),
                ('plant_type', models.TextField()),
                ('genus', models.TextField()),
                ('species', models.TextField()),
                ('latin_name', models.TextField()),
                ('common_name', models.TextField()),
                ('min_spread', models.FloatField()),
                ('max_spread', models.FloatField()),
                ('min_height', models.FloatField()),
                ('max_height', models.FloatField()),
                ('min_roots', models.FloatField()),
                ('max_roots', models.FloatField()),
                ('blooms_in_jan', models.BooleanField()),
                ('blooms_in_feb', models.BooleanField()),
                ('blooms_in_mar', models.BooleanField()),
                ('blooms_in_apr', models.BooleanField()),
                ('blooms_in_may', models.BooleanField()),
                ('blooms_in_jun', models.BooleanField()),
                ('blooms_in_jul', models.BooleanField()),
                ('blooms_in_aug', models.BooleanField()),
                ('blooms_in_sep', models.BooleanField()),
                ('blooms_in_oct', models.BooleanField()),
                ('blooms_in_nov', models.BooleanField()),
                ('blooms_in_dec', models.BooleanField()),
                ('min_life_cycle', models.IntegerField()),
                ('max_life_cycle', models.IntegerField()),
                ('light', models.TextField()),
                ('soil_ph', models.FloatField()),
                ('salt_tolerance', models.TextField()),
                ('drought_tolerance', models.TextField()),
                ('irrigation', models.TextField()),
                ('UOM', models.TextField()),
                ('material_cost', models.FloatField()),
                ('planting_cost', models.FloatField()),
                ('maintainence_cost_during_execution', models.FloatField()),
                ('maintainence_cost_after_initial_handing_over', models.FloatField()),
            ],
        ),
    ]
