from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Plant(models.Model):
    serial_number = models.CharField(max_length = 5, unique = True, blank = True)
    code = models.TextField(blank = True)
    classification = models.TextField(blank = True)
    plant_type = models.TextField(blank = True)
    genus = models.TextField(blank = True)
    species = models.TextField(blank = True)
    latin_name = models.TextField(blank = True)
    common_name = models.TextField(blank = True)
    min_spread = models.FloatField(blank = True)
    max_spread = models.FloatField(blank = True)
    min_height=  models.FloatField(blank = True)
    max_height = models.FloatField(blank = True)
    min_roots = models.FloatField(blank = True)
    max_roots = models.FloatField(blank = True)
    blooms_in_jan = models.BooleanField(blank = True)
    blooms_in_feb = models.BooleanField(blank = True)
    blooms_in_mar = models.BooleanField(blank = True)
    blooms_in_apr = models.BooleanField(blank = True)
    blooms_in_may = models.BooleanField(blank = True)
    blooms_in_jun = models.BooleanField(blank = True)
    blooms_in_jul = models.BooleanField(blank = True)
    blooms_in_aug = models.BooleanField(blank = True)
    blooms_in_sep = models.BooleanField(blank = True)
    blooms_in_oct = models.BooleanField(blank = True)
    blooms_in_nov = models.BooleanField(blank = True)
    blooms_in_dec = models.BooleanField(blank = True)
    min_life_cycle = models.IntegerField(blank = True)
    max_life_cycle = models.IntegerField(blank = True)
    light = models.TextField(blank = True)
    soil_ph = models.FloatField(blank = True)
    salt_tolerance = models.TextField(blank = True)
    drought_tolerance = models.TextField(blank = True)
    irrigation = models.TextField(blank = True)
    UOM = models.TextField(blank = True)
    material_cost = models.FloatField(blank = True)
    planting_cost = models.FloatField(blank = True)
    maintainence_cost_during_execution = models.FloatField(blank = True)
    maintainence_cost_after_initial_handing_over = models.FloatField(blank = True)
